# Basic set up for three package managers

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for gomod
  - package-ecosystem: "gomod"
    directory: "/client"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/fullnode"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/provider"
    schedule:
      interval: "daily"
    
  - package-ecosystem: "gomod"
    directory: "/verifier"
    schedule:
      interval: "daily"

  - package-ecosystem: "gomod"
    directory: "/ca"
    schedule:
      interval: "daily"