# mode(debug,test,release)
RunMode = "release"

# Whether to print configuration parameters at startup
PrintConfig = true

# Information about themselves
[App]
# Listening address
LocalAddr = "0.0.0.0"
# Listening port
LocalPort = 3091
# Control end address， "Used to obtain configuration or rule information"
ControlHost = "https://dash.cloudslit.xyz"

# w3s token
[Web3.W3s]
Token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkaWQ6ZXRocjoweDU4MUJkZEVGNTA3MDlmZjIzQzEwN0Q5YUU2NEVlMjc5M0IyMzk3NWMiLCJpc3MiOiJ3ZWIzLXN0b3JhZ2UiLCJpYXQiOjE2NTY2NDc2MDM2MjUsIm5hbWUiOiJjbG91ZHNsaXQifQ.7iUZuCDn1SNn7CxuR_kdAWf9_PfpuJlqPmy7ZdB2x9U"
# Request timeout (unit/second)
Timeout = 10
# Request failed retries
RetryCount = 100

[Log]
# level(1:fatal,2:error,3:warn,4:info,5:debug,6:trace)
Level = 4
# text、json
Format = "text"
# stdout、stderr、file
Output = "stdout"
OutputFile = "data/logger.log"
EnableHook = false
HookLevels = ["info", "warn", "error"]
# gorm、redis
Hook = "redis"
HookMaxThread = 1
HookMaxBuffer = 512

[LogRedisHook]
Addr = "127.0.0.1:6379"
Key = "log_key"

